curl -X GET http://192.168.2.223:8080/Expenses

curl -X POST http://192.168.2.222:8080/Expenses -H 'Content-Type: application/json' -d '{"id": 3, "fuel": 1, "date": "2022/05/13", "value": 10, "volume": 12, "odometer": 1945}'

curl -X DELETE http://192.168.2.222:8080/Expenses/3 -H 'Content-Type: application/json'

curl -X PATCH http://192.168.2.222:8080/Expenses/3 -H 'Content-Type: application/json' -d '{"id": 3, "fuel": 0, "date": "2022/12/25", "value": 10, "volume": 12, "odometer": 1945}'

### Registrar usuário
POST http://192.168.2.222:8080/register
Content-Type: application/json 
{
    "email": "renan.gsouza@pm.me",
    "password": "123"
}